language: ruby
rvm: 
  - 1.8.7
  - 1.9.2
  - ree
script: "rake spec"
branches:
  only:
    - master
    - travis-ci
env:
  - PUPPET_VERSION=2.6.14
  - PUPPET_VERSION=2.7.14
matrix:
  exclude:
    - rvm: 1.9.2
      env: PUPPET_VERSION=2.6.14